version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  data-vault-lint-test:
    working_directory: ~/tmp
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd data-vault
            - run: npm install
            - run: npm run test
            - run:
                name: Lint
                command: npm run lint:ci
            - run:
                name: Test
                command: npm run test:ci
                environment:
                  JEST_JUNIT_OUTPUT_DIR: ./reports/
            - store_test_results:
                path: ./reports/
            - store_artifacts:
                path: ./artifacts/

workflows:
    data-vault:
      jobs:
        - data-vault-lint-test
