FROM node:10

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY ./patch ./patch

RUN npm i
COPY ./patch/ethrDID-copy.js ./node_modules/ethr-did/lib/index.js

COPY ./src ./src
COPY ./tsconfig.json ./

RUN npm run build

EXPOSE 5101
EXPOSE 5100

CMD [ "node", ".\/build\/scripts\/all.js"]
