FROM node:10

WORKDIR /app

RUN wget https://github.com/ipfs/go-ipfs/releases/download/v0.6.0/go-ipfs_v0.6.0_linux-amd64.tar.gz

RUN tar -xvzf go-ipfs_v0.6.0_linux-amd64.tar.gz

RUN cd go-ipfs && \
    bash install.sh
RUN ipfs --version

RUN ipfs init

EXPOSE 8080
EXPOSE 5001
CMD [ "ipfs", "daemon"]
