FROM node:12

WORKDIR /app

RUN wget https://github.com/rsksmart/rif-data-vault/archive/refs/tags/v0.1.3.tar.gz

RUN tar -xvzf v0.1.3.tar.gz

RUN cd rif-data-vault-0.1.3 && \
    npm i && npm run setup 

WORKDIR /app/rif-data-vault-0.1.3/modules/ipfs-cpinner-service
EXPOSE 5102
CMD [ "npm", "run", "start"]